### ISSUE TITLE
Unlock type of architecture

### ISSUE THREAD

**Issue by trombini77** [idealo/cloudwatch-alarm-to-ms-teams#48]
Please is possible to remove the:
      Architectures:
        - arm64
into template.yaml because, for example exist regions that don´t have already support to arm64, in my case sa-east-1 doesn´t have it already?

**Comment by odinsey** [comment]
> Please is possible to remove the: Architectures: - arm64 into template.yaml because, for example exist regions that don´t have already support to arm64, in my case sa-east-1 doesn´t have it already?
As ap-east-1 either
